import os
import time
import subprocess
from pydub import AudioSegment
from pydub.effects import compress_dynamic_range, normalize

# ============================================================
# SILENCE MAP — Trailing silence duration per emotional style
# Controls pacing between lines far more precisely than a flat 300ms
# ============================================================
SILENCE_MAP = {
    "whisper":        900,
    "hushed":         850,
    "terrified":      700,
    "haunting":       1100,
    "chilling":       1000,
    "shocked":        550,
    "dramatic":       650,
    "cold":           200,
    "official":       160,
    "flat":           150,
    "document":       180,
    "fast":           100,
    "rapid":          80,
    "matter-of-fact": 150,
    "default":        300,
}

# ============================================================
# VOICE MAP — Upgraded to ElevenLabs IDs via Puter.js
# Maps speaker role → Public ElevenLabs Voice IDs
# ============================================================
VOICE_MAP = {
    "narrator": "VJwFZoxTZo5aI0IowiXA",  # David - Deep, Warm, and Steady
    "witness":  "iVwieylcLv7bwfinSNdw",  # Louise - Clear, calm, thoughtful
    "document": "ddiq1IkwhtAlQgobNKtj",  # John - Flat, Even and Consistent
    "reporter": "H538pP1BbhodCGiYVMKD",  # Harry - Articulate British Storyteller
}

# Failsafe: Intercepts legacy Gemini names generated by main.py
# ensuring the pipeline never breaks even if the LLM hallucinate old names
LEGACY_VOICE_MAP = {
    "Charon": VOICE_MAP["narrator"],
    "Kore":   VOICE_MAP["witness"],
    "Fenrir": VOICE_MAP["document"],
    "Puck":   VOICE_MAP["reporter"]
}

def get_style_silence(style_instruction: str) -> int:
    """Returns trailing silence (ms) matched to the emotional style of the line."""
    style_lower = style_instruction.lower()
    for key, duration in SILENCE_MAP.items():
        if key in style_lower:
            return duration
    return SILENCE_MAP["default"]


class VoiceEngine:
    def __init__(self):
        print("🎚️ Initializing ElevenLabs/Puter.js Master-Director Engine v3.0...")

        self.puter_token = os.environ.get("PUTER_AUTH_TOKEN")
        if not self.puter_token:
            raise ValueError("PUTER_AUTH_TOKEN environment variable not set. Required for free ElevenLabs generation.")

        # Dynamically generate the Node.js bridge file required for Puter
        self.bridge_file = "puter_tts_bridge.js"
        self._write_node_bridge()

    def _write_node_bridge(self):
        """Creates the headless Puter.js execution script."""
        node_code = """
import fs from 'fs/promises';
import { init } from "@heyputer/puter.js/src/init.cjs";

const token = process.env.PUTER_AUTH_TOKEN;
const puter = init(token);

const text = process.argv[2];
const voiceId = process.argv[3];
const outFile = process.argv[4];

async function generate() {
    try {
        const audio = await puter.ai.txt2speech(text, {
            provider: "elevenlabs",
            voice: voiceId,
            model: "eleven_multilingual_v2",
            output_format: "mp3_44100_128"
        });
        const buffer = Buffer.from(await audio.arrayBuffer());
        await fs.writeFile(outFile, buffer);
    } catch (error) {
        console.error("Puter Error:", error);
        process.exit(1);
    }
}
generate();
"""
        with open(self.bridge_file, "w", encoding="utf-8") as f:
            f.write(node_code.strip())

    # ----------------------------------------------------------
    # PROFESSIONAL 5-STAGE MASTERING CHAIN
    # ----------------------------------------------------------
    def _podcast_mastering(self, sound: AudioSegment, style_instruction: str = "default", clean_text: str | None = None) -> AudioSegment:
        """
        Stage 1 — High-Pass Filter (80Hz)
        Stage 2 — Low-Pass Filter (12 000Hz)
        Stage 3 — Dynamic Compression (podcast-grade settings)
        Stage 4 — Normalize to -0.2dBFS
        Stage 5 — Dynamic trailing silence mapped to emotion
        """
        sound = sound.high_pass_filter(80)
        sound = sound.low_pass_filter(12000)

        sound = compress_dynamic_range(
            sound,
            threshold=-14.0,
            ratio=4.5,
            attack=4.0,
            release=40.0
        )

        sound = normalize(sound, headroom=0.2)

        # Style-aware trailing silence
        silence_ms = get_style_silence(style_instruction)

        # Micro punctuation-aware adjustments
        if clean_text:
            tail = clean_text.strip()
            if tail.endswith("..."):
                silence_ms += 160
            elif tail.endswith("?"):
                silence_ms += 110
            elif tail.endswith("!"):
                silence_ms += 70
            elif "—" in tail or "-" in tail:
                silence_ms += 40

            word_count = len(tail.split())
            if word_count <= 6:
                silence_ms = max(80, silence_ms - 40)

        silence = AudioSegment.silent(duration=silence_ms)
        sound = sound + silence

        return sound

    # ----------------------------------------------------------
    # CORE GENERATION METHOD (ELEVENLABS)
    # ----------------------------------------------------------
    def generate_acting_line(
        self,
        acting_text: str,
        clean_text: str,
        style_instruction: str,
        index: int,
        voice_name: str = "Charon"
    ) -> str | None:
        """
        Renders one script line via ElevenLabs (Puter.js) and routes it through mastering.
        Ignores SSML acting_text to prevent ElevenLabs from reading XML tags aloud.
        """
        # 1. Resolve Voice ID mapping
        actual_voice_id = LEGACY_VOICE_MAP.get(voice_name, voice_name)
        if actual_voice_id not in VOICE_MAP.values():
            actual_voice_id = VOICE_MAP["narrator"]

        # 2. Text Payload (ElevenLabs natively infers brilliant emotion from punctuation)
        text_payload = clean_text.strip()
        if not text_payload:
            return None

        filename = f"temp_voice_{index}.wav"
        temp_raw = f"temp_raw_{index}.mp3"  # Puter returns mp3
        
        print(f"🎙️ Rendering ElevenLabs [{actual_voice_id}] | Style: {style_instruction[:55]}")

        # 3. Headless Node Execution with Retry Logic
        max_retries = 3
        success = False
        
        for attempt in range(max_retries):
            try:
                subprocess.run(
                    ["node", self.bridge_file, text_payload, actual_voice_id, temp_raw],
                    env=os.environ.copy(), # Injects PUTER_AUTH_TOKEN
                    check=True,
                    capture_output=True,
                    text=True
                )
                success = True
                break
            except subprocess.CalledProcessError as e:
                print(f"⚠️ Puter attempt {attempt + 1} failed: {e.stderr}")
                if attempt < max_retries - 1:
                    wait_time = 15 + (attempt * 10)
                    print(f"⏳ Waiting {wait_time}s to avoid rate limit...")
                    time.sleep(wait_time)
                else:
                    print(f"❌ All Puter TTS attempts exhausted for line {index}.")
                    return None

        if not success or not os.path.exists(temp_raw):
            return None

        # 4. Final Mastering
        try:
            # Load raw MP3
            sound = AudioSegment.from_file(temp_raw, format="mp3")
            
            # Master pipeline
            sound = self._podcast_mastering(sound, style_instruction, clean_text=text_payload)
            
            # Export clean WAV to be picked up by the Video Editor
            sound.export(filename, format="wav")

            if os.path.exists(temp_raw):
                os.remove(temp_raw)

            print(f"✅ Line {index} mastered ({actual_voice_id}) — {sound.duration_seconds:.1f}s")
            return filename

        except Exception as e:
            print(f"⚠️ Audio mastering failed on line {index}: {e}")
            return None
